### ISSUE TITLE
The packages in requirements.txt file seems mismatch with each other 

### ISSUE THREAD

**Issue by Astrology-Team** [zzshou/AMRSim#1]
1. The version of datasets==1.7.0, tokenizers==0.10.3 coflict with the transformers==4.24.0
transformers 4.24.0 requires huggingface-hub<1.0,>=0.10.0, but you have huggingface-hub 0.0.19 which is incompatible.
transformers 4.24.0 requires tokenizers!=0.11.3,<0.14,>=0.11.1, but you have tokenizers 0.10.3 which is incompatible.

2. The version of unidecode is confusing
In the requirements.txt, authors specify two versions of unidecode: unidecode==1.3.3, unidecode==1.3.6.
Which is true?

**Comment by Astrology-Team** [comment]
3. Could you please provide your version of CUDA and python?     orz

**Comment by zzshou** [comment]
thank for the comments. The issue is that we mistakenly added some unnecessary lines at the beginning of the requirements file, which caused confusion and led to the package version problems.
1. datasets is not needed in this project; tokenizers==0.13.2; transformers=4.24.0
2. unidecode==1.3.6
3. Python 3.7.10,  torch '1.12.0+cu102'
